### ISSUE TITLE
Users can't unselect "important" newsletters

### ISSUE THREAD

**Issue by nicholaschiang** [nicholaschiang/newsletter#15]
From @martinsrna:

> Bug: User cannot unselect a subscription in the “Relevant” section / check checked vs unchecked subscription for other issues

**Comment by jurajpal** [comment]
@nicholaschiang here's a video of the bug:
https://user-images.githubusercontent.com/8016147/116313621-d8bf9580-a762-11eb-8ffd-4f32a815e523.MOV

**Comment by nicholaschiang** [comment]
@jurajpal For some reason, all that I'm seeing is an audio file without any sound... But I think I know what you're talking about. The way that I have it written right now, this is the expected (but definitely undesired) behavior of the `useEffect` hook.

**Comment by jurajpal** [comment]
Does this work?
![image](https://user-images.githubusercontent.com/8016147/116488755-029eb800-a848-11eb-9547-309b440191bf.png)

**Comment by jurajpal** [comment]
Does this work?
![CleanShot 2021-04-28 at 20 34 19](https://user-images.githubusercontent.com/8016147/116488794-19450f00-a848-11eb-91e9-e21495bd418b.gif)
