### ISSUE TITLE
Sticky dates should be aligned with avatar

### ISSUE THREAD

**Issue by nicholaschiang** [nicholaschiang/newsletter#19]
From @martinsrna:

> Scrolling up in Feed should move the date only to the level of my profile, not all the way to the top/

This is the current (undesired) behavior that he's talking about:

https://user-images.githubusercontent.com/20798889/116295825-59c06200-a74e-11eb-8be8-742b4bbf957f.mov

And this is the desired behavior (from the [Figma prototype](https://www.figma.com/proto/968zBs03dtG5hS2pJOagcv/Newsletter-Reader-prototype?node-id=293%3A117&scaling=min-zoom&page-id=0%3A1):

https://user-images.githubusercontent.com/20798889/116296103-aad05600-a74e-11eb-926e-9a99b2a39acc.mov

**Comment by martinsrna** [comment]
The "Good morning.." should scroll and disappear, just the Date ("Today", etc.), should scroll to the same vertical position as that of the profile picture.
