### ISSUE TITLE
Replace navigation in reader page

### ISSUE THREAD

**Issue by nicholaschiang** [nicholaschiang/newsletter#20]
From @martinsrna:

> Replace the navigation in the reading mode with “Back”, “Share” and “Archive”
> - Automatically hides when scrolling and shows only 3 dots
> - Moving a cursor shows bar again

The navigation in the message page (i.e. the reader page) should look like this:

<img width="1133" alt="image" src="https://user-images.githubusercontent.com/20798889/116296365-00a4fe00-a74f-11eb-93c5-af417d3d6d26.png">

Those icons should disappear when scrolling down and then reappear when scrolling up or when "moving the cursor."

**Comment by nicholaschiang** [comment]
@martinsrna @jurajpal some questions for you:
- What should that "share" button do?
- What drop-down options are you thinking?
- What would be the behavior of each of those options?

I'm thinking that the easiest option for now would probably just to enable sharing of that reader page publicly (i.e. we make that message public and then anyone can access it from https://app.returnofthenewsletter.com/messages/asdfkjqdf). That would also be nice because then the people that they share the newsletter with will also be able to share in the amazing reading experience (that our app provides) and then they might sign up too!

**Comment by martinsrna** [comment]
Sorry for not elaborating on the Share button, that's definitely something for the (near term) future. Let's discuss how the link you suggest might work

**Comment by jurajpal** [comment]
Martin and I will chat about the link/public page but in the meantime, this is the thinking for the Share button:
![image](https://user-images.githubusercontent.com/8016147/116488640-b0f62d80-a847-11eb-883e-ebd9d6cb0916.png)

**Comment by nicholaschiang** [comment]
@jurajpal But that "copy link" button won't work right now (because only the person signed-in can view the `/messages/[id]` pages). And then what should the Twitter link do? I'm guessing you'll want to essentially just post a link to the newsletter on Twitter with some fancy previews and such... but... we can't do that until there's a way to publicly share the message page.

**Comment by martinsrna** [comment]
Let's skip the "Share" function for now, as it's directly impacting the reading and learning experience. We will shape it in the meantime.
